title: Learning to Code with Matt
author: Matthew Kohn
email: wanderkohn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a short blog about my self-taught coding journey.
# social links
twitter_username: MatthewKohn5 # DO NOT include the @ character, or else the build will fail!
github_username:  matthewkohn # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
